### ISSUE TITLE
Haddock syntax error in sdf2p1-parser-0.1

### ISSUE THREAD

**Issue by peti** [kojung/sdf2p1-parser#1]
According to our CI, http://hydra.cryp.to/build/525785/nixlog/2/raw, there's  a syntax error in the Haddock comments that causes the Haddock stage to fail:

```
src/Text/SDF/V2p1/Parser/SDFParser.hs:329:18:
    parse error on input ‘-- | The spec say port_path = (port | PATH hchar port), which simplifies to path’
```

**Comment by kojung** [comment]
Thank you! I fixed the typo and now Haddock looks happy. A new version has been released to Hackage.
